// Lightning Rendering Fragment Shader - BUFFER-BASED VERSION
// Reads lightning segments from buffer generated by compute shader

struct SimParams {
    delta_time: f32,
    friction: f32,
    num_particles: u32,
    num_types: u32,

    virtual_world_width: f32,
    virtual_world_height: f32,
    canvas_render_width: f32,
    canvas_render_height: f32,
    virtual_world_offset_x: f32,
    virtual_world_offset_y: f32,
    boundary_mode: u32,
    particle_render_size: f32,
    force_scale: f32,
    r_smooth: f32,
    flat_force: u32,
    drift_x_per_second: f32,
    inter_type_attraction_scale: f32,
    inter_type_radius_scale: f32,
    time: f32,
    fisheye_strength: f32,
    background_color_r: f32,
    background_color_g: f32,
    background_color_b: f32,

    // Lenia-inspired parameters
    lenia_enabled: u32,
    lenia_growth_mu: f32,
    lenia_growth_sigma: f32,
    lenia_kernel_radius: f32,

    // Lightning parameters
    lightning_frequency: f32,
    lightning_intensity: f32,
    lightning_duration: f32,

    // Particle transition parameters for GPU-based size transitions
    transition_active: u32,
    transition_start_time: f32,
    transition_duration: f32,
    transition_start_count: u32,
    transition_end_count: u32,
    transition_is_grow: u32,

    // Spatial grid optimization parameters
    spatial_grid_enabled: u32,
    spatial_grid_cell_size: f32,
    spatial_grid_width: u32,
    spatial_grid_height: u32,

    // Viewport/zoom parameters for rendering optimization
    viewport_center_x: f32,
    // Center of viewport in virtual world coordinates
    viewport_center_y: f32,
    // Center of viewport in virtual world coordinates
    viewport_width: f32,
    // Width of visible area in virtual world coordinates
    viewport_height: f32,
    // Height of visible area in virtual world coordinates
    viewport_radius: f32,
    // Radius of circular viewport in virtual world coordinates (for round screen)

    // Padding to ensure 16-byte alignment (3 × f32 = 12 bytes)
    _viewport_padding1: f32,
    _viewport_padding2: f32,
    _viewport_padding3: f32,
}

// Lightning segment data structure (must match compute shader)
struct LightningSegment {
    start_pos: vec2<f32>,
    // Segment start position (UV coordinates)
    end_pos: vec2<f32>,
    // Segment end position (UV coordinates)
    thickness: f32,
    // Segment thickness in UV units
    alpha: f32,
    // Segment alpha/opacity
    generation: u32,
    // Branch generation (0, 1, 2, 3)
    appear_time: f32,
    // When this segment should appear
    is_visible: u32,
    // 1 if visible, 0 if not (boolean as u32)
    _padding: u32,
    // Padding for alignment
    _padding2: u32,
    // Additional padding to align to 16-byte boundary (48 bytes total)
    _padding3: u32,
    // Final padding to reach 48 bytes (16-byte aligned)
}

// Lightning bolt data structure (must match compute shader)
struct LightningBolt {
    num_segments: u32,
    // Number of active segments in this bolt
    flash_id: u32,
    // Unique flash ID for this bolt
    start_time: f32,
    // When this bolt started
    next_lightning_time: f32,
    // When the next lightning should occur
    is_super_lightning: u32,
    // 1 if this is a super lightning, 0 if normal
    needs_rules_reset: u32,
    // 1 if interaction rules should be reset, 0 if not
    _padding1: u32,
    // Padding for 16-byte alignment
    _padding2: u32,
    // Additional padding
}

@group(0) @binding(0)
var<uniform> sim_params: SimParams;

@group(0) @binding(9)
var<storage, read> lightning_segments: array<LightningSegment>;

@group(0) @binding(10)
var<storage, read> lightning_bolt: LightningBolt;

// Helper function to draw a single segment in UV coordinates with improved anti-aliasing
fn drawSegment(uv: vec2<f32>, start: vec2<f32>, end: vec2<f32>, alpha: f32, thickness: f32, color: vec3<f32>) -> vec4<f32> {
    let segmentDir = end - start;
    let segmentLength = length(segmentDir);

    if (segmentLength < 0.001) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    let normalizedDir = segmentDir / segmentLength;
    let toPoint = uv - start;
    let projLength = dot(toPoint, normalizedDir);

    if (projLength >= 0.0 && projLength <= segmentLength) {
        let closestPoint = start + normalizedDir * projLength;
        let distToSegment = length(uv - closestPoint);

        // Improved anti-aliasing with soft falloff
        let halfThickness = thickness * 0.5;
        let antiAliasWidth = thickness * 0.3;
        // 30% of thickness for smooth falloff

        // Core intensity (full brightness within half thickness)
        let coreIntensity = 1.0 - smoothstep(0.0, halfThickness, distToSegment);

        // Soft edge falloff for anti-aliasing
        let edgeIntensity = 1.0 - smoothstep(halfThickness, halfThickness + antiAliasWidth, distToSegment);

        // Combine core and edge with different intensities
        let segmentIntensity = max(coreIntensity, edgeIntensity * 0.4) * alpha;

        return vec4<f32>(color, segmentIntensity);
    }

    return vec4<f32>(0.0, 0.0, 0.0, 0.0);
}

@fragment
fn main(@location(0) uv: vec2<f32>) -> @location(0) vec4<f32> {
    // UV coordinates are now passed directly from vertex shader (0.0 to 1.0)
    // No need to calculate or convert - pure UV system!

    // Early exit if lightning is disabled or no segments
    if (sim_params.lightning_frequency <= 0.0 || lightning_bolt.num_segments == 0u) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    var finalColor = vec3<f32>(1.0, 1.0, 1.0);
    var finalAlpha = 0.0;

    // Draw all segments from the buffer - segments are now in UV coordinates
    for (var i = 0u; i < lightning_bolt.num_segments; i++) {
        let segment = lightning_segments[i];

        // Skip invisible segments
        if (segment.is_visible == 0u) {
            continue;
        }

        // Simple white lightning - much cheaper than conditional color logic
        let segmentColor = vec3<f32>(1.0, 1.0, 1.0);
        let segmentResult = drawSegment(uv, segment.start_pos, segment.end_pos, segment.alpha, segment.thickness, segmentColor);

        // Accumulate lightning contributions
        finalColor += segmentResult.rgb;
        finalAlpha += segmentResult.a;
    }

    // Apply lightning intensity
    finalAlpha *= sim_params.lightning_intensity;

    if (finalAlpha <= 0.0) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    return vec4<f32>(finalColor, finalAlpha);
}
