// Lightning Rendering Fragment Shader - BUFFER-BASED VERSION
// Reads lightning segments from buffer generated by compute shader

struct SimulationParams {
    deltaTime: f32,
    friction: f32,
    numParticles: u32,
    numTypes: u32,
    virtualWorldWidth: f32,
    virtualWorldHeight: f32,
    canvasRenderWidth: f32,
    canvasRenderHeight: f32,
    virtualWorldOffsetX: f32,
    virtualWorldOffsetY: f32,
    boundaryMode: u32,
    particleRenderSize: f32,
    forceScale: f32,
    rSmooth: f32,
    flatForce: u32,
    driftXPerSecond: f32,
    interTypeAttractionScale: f32,
    interTypeRadiusScale: f32,
    time: f32,
    fisheyeStrength: f32,
    backgroundColor: vec3<f32>,

    // Lenia-inspired parameters
    leniaEnabled: u32,
    leniaGrowthMu: f32,
    leniaGrowthSigma: f32,
    leniaKernelRadius: f32,

    // Lightning parameters
    lightningFrequency: f32,
    lightningIntensity: f32,
    lightningDuration: f32,
}

// Lightning segment data structure (must match compute shader)
struct LightningSegment {
    startPos: vec2<f32>,
    // Segment start position (WORLD coordinates - converted to UV in rendering)
    endPos: vec2<f32>,
    // Segment end position (WORLD coordinates - converted to UV in rendering)
    thickness: f32,
    // Segment thickness in pixels
    alpha: f32,
    // Segment alpha/opacity
    generation: u32,
    // Branch generation (0, 1, 2, 3)
    appearTime: f32,
    // When this segment should appear
    isVisible: u32,
    // 1 if visible, 0 if not (boolean as u32)
    _padding: u32,
    // Padding for alignment
}

// Lightning bolt data structure (must match compute shader)
struct LightningBolt {
    numSegments: u32,
    // Number of active segments in this bolt
    flashId: u32,
    // Unique flash ID for this bolt
    startTime: f32,
    // When this bolt started
    _padding: u32,
    // Padding for alignment
}

@group(0) @binding(0)
var<uniform> sim_params: SimulationParams;

@group(0) @binding(1)
var<storage, read> lightning_segments: array<LightningSegment>;

@group(0) @binding(2)
var<storage, read> lightning_bolt: LightningBolt;

// Convert virtual world coordinates to UV coordinates
fn worldToUV(world: vec2<f32>) -> vec2<f32> {
    return vec2<f32>(world.x / sim_params.virtualWorldWidth, world.y / sim_params.virtualWorldHeight);
}

// Helper function to draw a single segment
fn drawSegment(uv: vec2<f32>, start: vec2<f32>, end: vec2<f32>, alpha: f32, thickness: f32) -> f32 {
    let segmentDir = end - start;
    let segmentLength = length(segmentDir);

    if (segmentLength < 0.001) {
        return 0.0;
    }

    let normalizedDir = segmentDir / segmentLength;
    let toPoint = uv - start;
    let projLength = dot(toPoint, normalizedDir);

    if (projLength >= 0.0 && projLength <= segmentLength) {
        let closestPoint = start + normalizedDir * projLength;
        let distToSegment = length(uv - closestPoint);

        let pixelThickness = thickness / 800.0;
        // Convert pixels to UV coordinates
        let segmentIntensity = (1.0 - smoothstep(0.0, pixelThickness, distToSegment)) * alpha;
        return segmentIntensity;
    }

    return 0.0;
}

@fragment
fn main(@builtin(position) frag_coord: vec4<f32>) -> @location(0) vec4<f32> {
    let resolution = vec2<f32>(sim_params.canvasRenderWidth, sim_params.canvasRenderHeight);
    let uv = frag_coord.xy / resolution;

    // Check if lightning is enabled
    if (sim_params.lightningFrequency <= 0.0) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    // Calculate lightning timing using proper parameters
    let flashInterval = 1.0 / sim_params.lightningFrequency;
    let timeInCycle = sim_params.time % flashInterval;
    let flashDuration = sim_params.lightningDuration;

    // Only show lightning during flash period
    if (timeInCycle > flashDuration) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    var boltIntensity = 0.0;

    // Draw all segments from the buffer
    for (var i = 0u; i < lightning_bolt.numSegments; i++) {
        let segment = lightning_segments[i];

        // Only draw visible segments
        if (segment.isVisible != 0u) {
            // Convert world coordinates to UV coordinates for rendering
            let startUV = worldToUV(segment.startPos);
            let endUV = worldToUV(segment.endPos);

            let segmentIntensity = drawSegment(uv, startUV, endUV, segment.alpha, segment.thickness);
            boltIntensity = max(boltIntensity, segmentIntensity);
        }
    }

    if (boltIntensity <= 0.0) {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }

    // Lightning color - bright blue-white
    let lightningColor = vec3<f32>(0.8, 0.9, 1.0);
    let alpha = boltIntensity * sim_params.lightningIntensity;

    return vec4<f32>(lightningColor, alpha);
}
