#!/usr/bin/env node
// Copyright © 2025 - 2026 Michel Reij | Bewogen Kunst | Moving Art
// Licensed under CC BY-NC 4.0 — https://creativecommons.org/licenses/by-nc/4.0/
//
// Reads life_params.json → generates:
//   gen/life_params.ts   (TypeScript, for particle-life embed + UI)
//   gen/life_params.h    (C header, for meters + platformio)
//   gen/life_params.rs   (Rust module, for particle-life WASM)

"use strict";

const fs   = require("fs");
const path = require("path");

const src  = path.join(__dirname, "life_params.json");
const outDir = path.join(__dirname, "..", "src", "gen");
fs.mkdirSync(outDir, { recursive: true });

const data = JSON.parse(fs.readFileSync(src, "utf8"));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pct(value, min, max) {
    return ((value - min) / (max - min)) * 100;
}

// Convert a ranges array (physical units) to Stop[] (percent + hue).
// A "transition" range is expanded into two stops: start and end, each with
// the hue of the neighboring region, so gradientColor() can interpolate.
function rangesToStops(ranges, min, max, oklch) {
    const { h_blue, h_green, h_yellow, h_red } = oklch;
    const colorHue = { blue: h_blue, green: h_green, yellow: h_yellow, red: h_red };

    const stops = [];
    for (let i = 0; i < ranges.length; i++) {
        const r = ranges[i];
        const pMin = pct(r.min, min, max);
        const pMax = pct(r.max, min, max);

        if (r.color === "transition") {
            // Hue of the range before and after this transition
            const hFrom = i > 0 ? colorHue[ranges[i - 1].color] : h_red;
            const hTo   = i < ranges.length - 1 ? colorHue[ranges[i + 1].color] : h_red;
            stops.push([pMin, hFrom]);
            stops.push([pMax, hTo]);
        } else {
            const h = colorHue[r.color];
            stops.push([pMin, h]);
            stops.push([pMax, h]);
        }
    }

    // Deduplicate consecutive stops at the same percentage
    const deduped = [stops[0]];
    for (let i = 1; i < stops.length; i++) {
        if (Math.abs(stops[i][0] - deduped[deduped.length - 1][0]) > 0.001) {
            deduped.push(stops[i]);
        }
    }
    return deduped;
}

// Convert explicit css_stops [{min, color}] in physical units to Stop[] percents
function cssStopsToStops(cssStops, min, max, oklch) {
    const { h_blue, h_green, h_yellow, h_red } = oklch;
    const colorHue = { blue: h_blue, green: h_green, yellow: h_yellow, red: h_red };
    return cssStops.map(([val, color]) => [pct(val, min, max), colorHue[color]]);
}

// CSS gradient string from stops, direction "to top" (default for vertical sliders)
function stopsToGradient(stops, oklch, direction = "to top") {
    const { l, c } = oklch;
    const parts = stops.map(([p, h]) => `oklch(${l} ${c} ${h}) ${p.toFixed(1)}%`);
    return `linear-gradient(in oklch ${direction}, ${parts.join(", ")})`;
}

// ---------------------------------------------------------------------------
// Derive colour_zone_t values for C (red_lo, green_lo, green_hi, red_hi)
// These are the first/last physical values of transition regions.
// ---------------------------------------------------------------------------
function colourZone(ranges) {
    let red_lo = null, green_lo = null, green_hi = null, red_hi = null;
    for (const r of ranges) {
        if (r.color === "green") {
            if (green_lo === null) green_lo = r.min;
            green_hi = r.max;
        }
        if (r.color === "transition") {
            // First transition after red → becomes red_lo
            if (green_lo === null && red_lo === null) red_lo = r.min;
            // Last transition before terminal red → red_hi
            red_hi = r.max;
        }
    }
    // Fallback for sliders that start/end in red (no leading transition)
    if (red_lo === null) red_lo = ranges[0].min;
    if (red_hi === null) red_hi = ranges[ranges.length - 1].max;
    return { red_lo, green_lo, green_hi, red_hi };
}

// ---------------------------------------------------------------------------
// TypeScript output
// ---------------------------------------------------------------------------

function genTS() {
    const { oklch, sliders } = data;
    const lines = [];
    lines.push(`// AUTO-GENERATED by shared/codegen.js — DO NOT EDIT MANUALLY`);
    lines.push(`// Source: shared/life_params.json`);
    lines.push(``);
    lines.push(`export const OKLCH_L = ${oklch.l};`);
    lines.push(`export const OKLCH_C = ${oklch.c};`);
    lines.push(`export const H_BLUE   = ${oklch.h_blue};`);
    lines.push(`export const H_GREEN  = ${oklch.h_green};`);
    lines.push(`export const H_YELLOW = ${oklch.h_yellow};`);
    lines.push(`export const H_RED    = ${oklch.h_red};`);
    lines.push(``);
    lines.push(``);
    lines.push(`export type Stop = [number, number]; // [percent, hue]`);
    lines.push(``);
    lines.push(`export interface SliderVariant {`);
    lines.push(`    min: number;`);
    lines.push(`    max: number;`);
    lines.push(`    step: number;`);
    lines.push(`    label: Record<string, string>;`);
    lines.push(`    unit: Record<string, string>;`);
    lines.push(`    stops: Stop[];`);
    lines.push(`    gradient: string; // CSS linear-gradient string`);
    lines.push(`    optimum: number | null;`);
    lines.push(`    snapToMinThreshold: number | null;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export const SLIDERS: { htv: SliderVariant; wlp: SliderVariant }[] = [`);

    for (const slider of sliders) {
        lines.push(`    {`);
        for (const hyp of ["htv", "wlp"]) {
            const v = slider[hyp];
            const min  = v.min  ?? slider.min;
            const max  = v.max  ?? slider.max;
            const step = v.step ?? slider.step;
            const stops = v.css_stops
                ? cssStopsToStops(v.css_stops, min, max, oklch)
                : rangesToStops(v.ranges, min, max, oklch);
            const gradient = stopsToGradient(stops, oklch);
            const optimum  = v.optimum !== undefined ? v.optimum : null;
            const snap     = v.snap_to_min_threshold !== undefined ? v.snap_to_min_threshold : null;
            lines.push(`        ${hyp}: {`);
            lines.push(`            min: ${min}, max: ${max}, step: ${step},`);
            lines.push(`            label: ${JSON.stringify(v.labels)},`);
            lines.push(`            unit: ${JSON.stringify(v.units)},`);
            lines.push(`            stops: ${JSON.stringify(stops)},`);
            lines.push(`            gradient: ${JSON.stringify(gradient)},`);
            lines.push(`            optimum: ${JSON.stringify(optimum)},`);
            lines.push(`            snapToMinThreshold: ${JSON.stringify(snap)},`);
            lines.push(`        },`);
        }
        lines.push(`    },`);
    }

    lines.push(`];`);
    lines.push(``);

    // Export UV sigma_sq constant
    const s2wlp = sliders[2].wlp;
    if (s2wlp.sigma_sq !== undefined) {
        lines.push(`export const UV_SIGMA_SQ = ${s2wlp.sigma_sq};`);
    }

    return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// C header output
// ---------------------------------------------------------------------------

function genC() {
    const { oklch, sliders } = data;
    const lines = [];
    lines.push(`/* AUTO-GENERATED by shared/codegen.js — DO NOT EDIT MANUALLY */`);
    lines.push(`/* Source: shared/life_params.json */`);
    lines.push(`#ifndef LIFE_PARAMS_H`);
    lines.push(`#define LIFE_PARAMS_H`);
    lines.push(``);
    lines.push(`#include <stdint.h>`);
    lines.push(`#include <math.h>`);
    lines.push(``);
    lines.push(`/* OkLCH colour constants — single source of truth from life_params.json */`);
    const cf = v => Number.isInteger(v) ? `${v}.0f` : `${v}f`;
    lines.push(`#define OKLCH_L   ${cf(oklch.l)}`);
    lines.push(`#define OKLCH_C   ${cf(oklch.c)}`);
    lines.push(`#define H_BLUE    ${cf(oklch.h_blue)}`);
    lines.push(`#define H_GREEN   ${cf(oklch.h_green)}`);
    lines.push(`#define H_YELLOW  ${cf(oklch.h_yellow)}`);
    lines.push(`#define H_RED     ${cf(oklch.h_red)}`);
    lines.push(``);
    lines.push(`#define NUM_SLIDERS 4`);
    lines.push(``);

    // Hypothesis enum
    lines.push(`typedef enum { HYPO_HTV = 0, HYPO_WLP = 1 } hypothesis_t;`);
    lines.push(``);

    // Colour zone struct
    lines.push(`typedef struct {`);
    lines.push(`    float red_lo, green_lo, green_hi, red_hi;`);
    lines.push(`} colour_zone_t;`);
    lines.push(``);

    // Slider meta struct
    lines.push(`typedef struct {`);
    lines.push(`    float min, max, step;`);
    lines.push(`    const char *label_nl, *label_en, *label_fr;`);
    lines.push(`    const char *unit_nl,  *unit_en,  *unit_fr;`);
    lines.push(`    colour_zone_t zone;`);
    lines.push(`    float optimum;           /* optimal physical value */`);
    lines.push(`    float snap_to_min_threshold; /* snap to min when value < this; NAN = disabled */`);
    lines.push(`} slider_def_t;`);
    lines.push(``);

    // Generate per-hypothesis arrays
    for (const hyp of ["htv", "wlp"]) {
        lines.push(`static const slider_def_t SLIDER_DEFS_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        for (const slider of sliders) {
            const v    = slider[hyp];
            const min  = v.min  ?? slider.min;
            const max  = v.max  ?? slider.max;
            const step = v.step ?? slider.step;
            const z    = colourZone(v.ranges);
            const opt  = v.optimum !== undefined ? cf(v.optimum) : `NAN`;
            const snap = v.snap_to_min_threshold !== undefined ? cf(v.snap_to_min_threshold) : `NAN`;
            lines.push(`    /* slider ${slider.index} */`);
            lines.push(`    { ${cf(min)}, ${cf(max)}, ${cf(step)},`);
            lines.push(`      "${v.labels.nl}", "${v.labels.en}", "${v.labels.fr}",`);
            lines.push(`      "${v.units.nl}", "${v.units.en}", "${v.units.fr}",`);
            lines.push(`      { ${cf(z.red_lo)}, ${cf(z.green_lo)}, ${cf(z.green_hi)}, ${cf(z.red_hi)} },`);
            lines.push(`      ${opt}, ${snap} },`);
        }
        lines.push(`};`);
        lines.push(``);
    }

    // UV sigma_sq constant (gaussian curve for UV fitness function)
    const s2wlp = sliders[2].wlp;
    if (s2wlp.sigma_sq !== undefined) {
        lines.push(`#define UV_SIGMA_SQ ${cf(s2wlp.sigma_sq)}`);
        lines.push(``);
    }

    // Convenience macro to select active def
    lines.push(`#define SLIDER_DEF(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_DEFS_WLP[(idx)] : SLIDER_DEFS_HTV[(idx)])`);
    lines.push(``);

    // Enum of all known parameters (hypothesis-independent identifiers)
    const allParams = [...new Set(
        sliders.flatMap(s => ["htv", "wlp"].map(h => s[h].param))
    )];
    lines.push(`typedef enum {`);
    allParams.forEach((p, i) => lines.push(`    LIFE_PARAM_${p.toUpperCase()} = ${i},`));
    lines.push(`} life_param_t;`);
    lines.push(``);

    // Physical slider index → param, per hypothesis
    for (const hyp of ["htv", "wlp"]) {
        lines.push(`/* Physical slider index → parameter for ${hyp.toUpperCase()} */`);
        lines.push(`static const life_param_t SLIDER_PARAM_MAP_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        for (const slider of sliders) {
            const param = slider[hyp].param;
            lines.push(`    LIFE_PARAM_${param.toUpperCase()}, /* slider ${slider.index} */`);
        }
        lines.push(`};`);
        lines.push(``);
    }

    // Physical min/max per slider per hypothesis (for raw→physical conversion)
    for (const hyp of ["htv", "wlp"]) {
        lines.push(`static const float SLIDER_PHYS_MIN_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        lines.push(`    ` + sliders.map(s => {
            const v = s[hyp]; const min = v.min ?? s.min;
            return `${cf(min)} /* slider ${s.index}: ${v.param} */`;
        }).join(", "));
        lines.push(`};`);
        lines.push(`static const float SLIDER_PHYS_MAX_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        lines.push(`    ` + sliders.map(s => {
            const v = s[hyp]; const max = v.max ?? s.max;
            return `${cf(max)} /* slider ${s.index}: ${v.param} */`;
        }).join(", "));
        lines.push(`};`);
        lines.push(``);
    }

    // Optimum and snap-to-min threshold per slider per hypothesis (NAN = not applicable)
    for (const hyp of ["htv", "wlp"]) {
        lines.push(`static const float SLIDER_OPTIMUM_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        lines.push(`    ` + sliders.map(s => {
            const v = s[hyp];
            const opt = v.optimum !== undefined ? cf(v.optimum) : `NAN`;
            return `${opt} /* slider ${s.index}: ${v.param} */`;
        }).join(", "));
        lines.push(`};`);
        lines.push(`static const float SLIDER_SNAP_THRESHOLD_${hyp.toUpperCase()}[NUM_SLIDERS] = {`);
        lines.push(`    ` + sliders.map(s => {
            const v = s[hyp];
            const snap = v.snap_to_min_threshold !== undefined ? cf(v.snap_to_min_threshold) : `NAN`;
            return `${snap} /* slider ${s.index}: ${v.param} */`;
        }).join(", "));
        lines.push(`};`);
        lines.push(``);
    }

    // Convenience macros
    lines.push(`#define SLIDER_PARAM(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_PARAM_MAP_WLP[(idx)] : SLIDER_PARAM_MAP_HTV[(idx)])`);
    lines.push(`#define SLIDER_PHYS_MIN(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_PHYS_MIN_WLP[(idx)] : SLIDER_PHYS_MIN_HTV[(idx)])`);
    lines.push(`#define SLIDER_PHYS_MAX(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_PHYS_MAX_WLP[(idx)] : SLIDER_PHYS_MAX_HTV[(idx)])`);
    lines.push(`#define SLIDER_OPTIMUM(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_OPTIMUM_WLP[(idx)] : SLIDER_OPTIMUM_HTV[(idx)])`);
    lines.push(`#define SLIDER_SNAP_THRESHOLD(hyp, idx) \\`);
    lines.push(`    ((hyp) == HYPO_WLP ? SLIDER_SNAP_THRESHOLD_WLP[(idx)] : SLIDER_SNAP_THRESHOLD_HTV[(idx)])`);
    lines.push(``);
    lines.push(`#endif /* LIFE_PARAMS_H */`);

    return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Rust output
// ---------------------------------------------------------------------------

function genRust() {
    const { sliders, oklch } = data;
    const lines = [];
    lines.push(`// AUTO-GENERATED by shared/codegen.js — DO NOT EDIT MANUALLY`);
    lines.push(`// Source: shared/life_params.json`);
    lines.push(``);
    lines.push(`pub const WLP_DEPTH_THRESHOLD: f32 = ${data.wlp_depth_threshold}.0;`);
    lines.push(``);
    const f32 = v => Number.isInteger(v) ? `${v}.0` : `${v}`;
    lines.push(`// OKLCH hue-waarden (slider-kleurschema)`);
    lines.push(`pub const H_BLUE:   f32 = ${f32(oklch.h_blue)};`);
    lines.push(`pub const H_GREEN:  f32 = ${f32(oklch.h_green)};`);
    lines.push(`pub const H_YELLOW: f32 = ${f32(oklch.h_yellow)};`);
    lines.push(`pub const H_RED:    f32 = ${f32(oklch.h_red)};`);
    lines.push(``);
    lines.push(`// OKLCH L/C voor simulatie-achtergrond (lichter en minder verzadigd dan slider-thumb)`);
    lines.push(`pub const BACKGROUND_L_HTV: f32 = ${f32(oklch.background_l_htv)};`);
    lines.push(`pub const BACKGROUND_C_HTV: f32 = ${f32(oklch.background_c_htv)};`);
    lines.push(`pub const BACKGROUND_L_WLP: f32 = ${f32(oklch.background_l_wlp)};`);
    lines.push(`pub const BACKGROUND_C_WLP: f32 = ${f32(oklch.background_c_wlp)};`);
    lines.push(``);

    const s2wlp = sliders[2].wlp;
    if (s2wlp.uv_optimum !== undefined) {
        lines.push(`pub const UV_OPTIMUM:  f32 = ${f32(s2wlp.uv_optimum)};`);
        lines.push(`pub const UV_SIGMA_SQ: f32 = ${f32(s2wlp.uv_sigma_sq)};`);
        lines.push(``);
    }

    // Physical ranges per slider, per hypothesis
    for (const hyp of ["htv", "wlp"]) {
        lines.push(`pub mod ${hyp} {`);
        for (const slider of sliders) {
            const v   = slider[hyp];
            const min = v.min  ?? slider.min;
            const max = v.max  ?? slider.max;
            const i   = slider.index;
            lines.push(`    pub const SLIDER${i}_MIN: f32 = ${min}.0;`);
            lines.push(`    pub const SLIDER${i}_MAX: f32 = ${max}.0;`);
        }
        lines.push(`}`);
        lines.push(``);
    }

    return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Write files
// ---------------------------------------------------------------------------

fs.writeFileSync(path.join(outDir, "life_params.ts"), genTS());
console.log("✓ src/gen/life_params.ts");

const cOutDir = path.join(__dirname, "gen");
fs.mkdirSync(cOutDir, { recursive: true });
const cHeader = genC();
fs.writeFileSync(path.join(cOutDir, "life_params.h"),  cHeader);
fs.writeFileSync(path.join(cOutDir, "life_params.rs"), genRust());
console.log("✓ shared/gen/life_params.h");
console.log("✓ shared/gen/life_params.rs");

const platformioInclude = path.join(__dirname, "../../../platformio/include/life_params.h");
if (fs.existsSync(path.dirname(platformioInclude))) {
    fs.writeFileSync(platformioInclude, cHeader);
    console.log("✓ platformio/include/life_params.h");
}

const metersInclude = path.join(__dirname, "../../../meters/main/life_params.h");
if (fs.existsSync(path.dirname(metersInclude))) {
    fs.writeFileSync(metersInclude, cHeader);
    console.log("✓ meters/main/life_params.h");
}
